name = "Cheapslate"
author = "cozyGalvinism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "238c662662910a41edda2bba7a22a69dd1d94e9dd6e8d744cd529e1e8bf42a71"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
